import { NextPage } from 'next'
import Head from 'next/head'
import { ReactNode } from 'react'
import { getTemporaryToken } from 'src/helpers/storage'
import LayoutNotApp from 'src/view/layout/LayoutNotApp'
import HomePage from 'src/view/pages/home'

type TProps = {}

const Home: NextPage<TProps> = () => {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomePage />
    </>
  )
}

Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
Home.guestGuard = false
Home.authGuard = false

export default Home
