import { NextPage } from 'next'
import Head from 'next/head'
import { ReactNode } from 'react'
import CustomDataGrid from 'src/components/custom-data-grid'
import { getTemporaryToken } from 'src/helpers/storage'
import LayoutNotApp from 'src/view/layout/LayoutNotApp'

export default function Home() {
  const temporaryToken = getTemporaryToken()

  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
Home.guestGuard = false
Home.authGuard = false
