'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import { Typography } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Typography>Test CI/CD</Typography>
      <Button variant='contained'>Hello world</Button>
    </>
  )
}
